"""
Unit tests for BaseRepository.create() and update() methods.

Verifies:
- create() inserts + flushes + refreshes entity, returning it with PK
- update() stages an existing entity for update without flush
- Both methods coexist with existing add() for backward compatibility
"""
import pytest
from datetime import datetime
from sqlmodel import SQLModel, Session, Field, create_engine, select
from sqlalchemy.pool import StaticPool

from app.core.base_repository import BaseRepository
from app.core.base import SoftDeleteModel, get_utc_now


# ── Test model ──────────────────────────────────────────────────────────
class Widget(SQLModel, table=True):
    """Simple model for testing repository operations."""
    __tablename__ = "test_widget"
    id: int | None = Field(default=None, primary_key=True)
    name: str
    created_at: datetime = Field(default_factory=get_utc_now)


class SoftWidget(SoftDeleteModel, table=True):
    """Soft-deletable model for testing soft-delete repo ops."""
    __tablename__ = "test_soft_widget"
    id: int | None = Field(default=None, primary_key=True)
    name: str


@pytest.fixture(scope="function")
def engine():
    """Create an in-memory SQLite engine with StaticPool for tests."""
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    SQLModel.metadata.create_all(engine)
    return engine


@pytest.fixture(scope="function")
def session(engine):
    """Create a transactional session that rolls back after each test."""
    connection = engine.connect()
    transaction = connection.begin()
    session = Session(bind=connection)
    yield session
    session.close()
    transaction.rollback()
    connection.close()


@pytest.fixture
def repo(session):
    """BaseRepository[Widget] wired to the test session."""
    return BaseRepository[Widget](session, Widget)


@pytest.fixture
def soft_repo(session):
    """BaseRepository[SoftWidget] wired to the test session."""
    return BaseRepository[SoftWidget](session, SoftWidget)


# ── Tests: create() ─────────────────────────────────────────────────────

class TestCreate:
    """RED phase: tests for BaseRepository.create()."""

    def test_create_inserts_and_returns_with_pk(self, repo, session):
        """create() must flush + refresh and return entity with generated PK."""
        widget = Widget(name="test-widget")
        result = repo.create(widget)

        # Must return the same entity object
        assert result is widget
        # PK must be populated after flush+refresh
        assert result.id is not None
        # Entity must be persistent (queryable)
        found = session.exec(select(Widget).where(Widget.id == result.id)).first()
        assert found is not None
        assert found.name == "test-widget"

    def test_create_fills_autogenerated_fields(self, repo, session):
        """create() must populate auto-generated fields like created_at."""
        widget = Widget(name="auto-fields")
        result = repo.create(widget)

        # created_at must be populated by flush+refresh
        assert result.created_at is not None
        assert isinstance(result.created_at, datetime)

    def test_create_two_different_widgets(self, repo, session):
        """Triangulation: two creates must produce distinct IDs."""
        w1 = Widget(name="first")
        w2 = Widget(name="second")

        r1 = repo.create(w1)
        r2 = repo.create(w2)

        assert r1.id != r2.id
        # Verify both persisted
        count = session.exec(select(Widget)).all()
        assert len(count) == 2


# ── Tests: update() ─────────────────────────────────────────────────────

class TestUpdate:
    """RED phase: tests for BaseRepository.update()."""

    def test_update_stages_existing_entity(self, repo, session):
        """update() must stage an existing entity for update without flush."""
        # First, create a widget
        widget = Widget(name="original")
        session.add(widget)
        session.flush()
        session.refresh(widget)

        # Now modify and call update()
        widget.name = "modified"
        result = repo.update(widget)

        # Must return the same entity
        assert result is widget
        assert result.name == "modified"

        # Entity should still be in session (staged, not committed yet)
        # Flush to verify the change is pending
        session.flush()
        found = session.exec(select(Widget).where(Widget.id == widget.id)).first()
        assert found is not None
        assert found.name == "modified"

    def test_update_does_not_change_pk(self, repo, session):
        """Triangulation: update() must not modify the PK of the entity."""
        widget = Widget(name="pk-test")
        session.add(widget)
        session.flush()
        session.refresh(widget)
        original_id = widget.id

        widget.name = "pk-changed-name"
        repo.update(widget)

        assert widget.id == original_id


# ── Tests: backward compatibility ───────────────────────────────────────

class TestBackwardCompatibility:
    """Verify existing add() still works after create()/update() addition."""

    def test_add_still_works(self, repo, session):
        """add() must still stage an entity without flush."""
        widget = Widget(name="via-add")
        result = repo.add(widget)

        assert result is widget
        # PK is None because add() doesn't flush
        assert result.id is None

    def test_add_then_flush_matches_create_behavior(self, repo, session):
        """add() + flush() + refresh() should be equivalent to create()."""
        widget = Widget(name="manual-cycle")
        repo.add(widget)
        repo.flush()
        repo.refresh(widget)

        assert widget.id is not None
        assert widget.created_at is not None
