"""add precio_actual to producto

#Template para crear nuevas versiones automaticamente.

Revision ID: 448487941269
Revises: 3a5b8c9d0e1f
Create Date: 2026-06-05 20:25:50.463960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448487941269'
down_revision: Union[str, Sequence[str], None] = '3a5b8c9d0e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('precio_actual', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'precio_actual')
    # ### end Alembic commands ###
