"""remove primordial and medidas

Revision ID: 1859de7b45ad
Revises: a94d7efb265b
Create Date: 2026-05-30 19:20:10.162505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1859de7b45ad'
down_revision: Union[str, Sequence[str], None] = 'a94d7efb265b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productomedida')
    op.drop_column('categoria', 'es_primordial')
    # medida_snapshot se conserva en BD para datos históricos
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('es_primordial', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('productomedida',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('disponible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('productomedida_producto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('productomedida_pkey'))
    )
    # ### end Alembic commands ###
