"""Initial schema creation.

Creates the base tables for the Food Store platform:
- Adds precio_actual and stock_actual columns to the existing ingrediente table.
- Adds the cantidad column to the productoingrediente join table.

This migration was auto-generated by Alembic after running
`alembic revision --autogenerate` with the initial model definitions loaded.

Revision ID: a94d7efb265b
Revises: (none -- this is the first migration)
Create Date: 2026-05-30 19:09:35.462076
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94d7efb265b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the initial schema changes.

    Add columns to existing tables that were created manually in the database
    but needed tracking fields for pricing and stock management.
    """
    # Track the current unit price of each ingredient (nullable for items
    # where pricing is not applicable or not yet configured).
    op.add_column('ingrediente', sa.Column('precio_actual', sa.Numeric(precision=10, scale=2), nullable=True))
    # Track current stock level for each ingredient; default to 0 on creation.
    op.add_column('ingrediente', sa.Column('stock_actual', sa.Integer(), nullable=False, server_default='0'))
    # Quantity of an ingredient used in a product, stored as a decimal.
    op.add_column('productoingrediente', sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=True))


def downgrade() -> None:
    """Revert the initial schema changes by removing the added columns."""
    op.drop_column('productoingrediente', 'cantidad')
    op.drop_column('ingrediente', 'stock_actual')
    op.drop_column('ingrediente', 'precio_actual')
