"""initial schema

Revision ID: a94d7efb265b
Revises: 
Create Date: 2026-05-30 19:09:35.462076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94d7efb265b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingrediente', sa.Column('precio_actual', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ingrediente', sa.Column('stock_actual', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('productoingrediente', sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productoingrediente', 'cantidad')
    op.drop_column('ingrediente', 'stock_actual')
    op.drop_column('ingrediente', 'precio_actual')
    # ### end Alembic commands ###
